// PM2 ecosystem — SAVYRON
// Uso: pm2 start ecosystem.config.js && pm2 save && pm2 startup
module.exports = {
  apps: [
    {
      name: "prospector-dashboard",
      cwd: __dirname + "/apps/dashboard",
      script: "node_modules/.bin/next",
      args: "start -p 3005",
      instances: 1,
      autorestart: true,
      max_memory_restart: "512M",
      env: { NODE_ENV: "production" },
      out_file: __dirname + "/logs/dashboard.out.log",
      error_file: __dirname + "/logs/dashboard.err.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "prospector-api",
      cwd: __dirname + "/apps/api",
      script: "dist/index.js",
      instances: 1,
      autorestart: true,
      max_memory_restart: "512M",
      env: { NODE_ENV: "production" },
      out_file: __dirname + "/logs/api.out.log",
      error_file: __dirname + "/logs/api.err.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "prospector-worker",
      cwd: __dirname + "/apps/worker",
      script: "dist/index.js",
      instances: 1,
      autorestart: true,
      max_memory_restart: "512M",
      env: { NODE_ENV: "production" },
      out_file: __dirname + "/logs/worker.out.log",
      error_file: __dirname + "/logs/worker.err.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "prospector-scrapy",
      cwd: __dirname + "/services/scrapy",
      script: "server.py",
      interpreter: __dirname + "/services/scrapy/.venv/bin/python",
      instances: 1,
      autorestart: true,
      max_memory_restart: "512M",
      env: {
        SCRAPY_SERVICE_PORT: "6810",
        SCRAPY_CONCURRENCY: "2",
        SCRAPY_REQUEST_DELAY_MS: "1000",
        NODE_ENV: "production",
      },
      out_file: __dirname + "/logs/scrapy.out.log",
      error_file: __dirname + "/logs/scrapy.err.log",
      merge_logs: true,
      time: true,
    },
  ],
};
